### ISSUE TITLE
How to restore the trainning

### ISSUE THREAD

**Issue by robeson1010** [neptune-ml/open-solution-mapping-challenge#160]
I have trained the data for 3 days but unfortunately the processing interrupted due to some reasons. I have used the 'python main.py -- train --pipeline_name unet_weighted' but it trained from epochs 0. How can I restore the training processing from my last time (54 epochs already)?

**Comment by robeson1010** [comment]
@jakubczakon  Really thanks

**Comment by carbonox-infernox** [comment]
@jakubczakon 

"As of now we are not checkpointing the optimizer state so it will be difficult to restore the exact state of your training"

Is this still the case? I was hoping to run the training 5-10 epochs at a time and keep checking on the model's progress. Then I'd like to add some new classes, but that's a different problem. Basically I don't want to pay for the full 100 and then find out that something went wrong, or otherwise pay for 100 when 50 might suffice.
