### ISSUE TITLE
how the pixel-wise segmentation maps are converted to object-wise instances?

### ISSUE THREAD

**Issue by lixiang-ucas** [neptune-ml/open-solution-mapping-challenge#164]
Where can I find the code for converting the pixel-wise segmentation maps to object-wise instances? I've checked the 'create_annotations' in utils.py, it seems that you generate instances of the same category all together using 'rle_from_binary' function. I'd like to know how the instances of the same category are separated? Thank you!

**Comment by taraspiotr** [comment]
Hi @lixiang-ucas 
Object instances are created by the step `labeler`:
https://github.com/neptune-ml/open-solution-mapping-challenge/blob/865f37571a844d698ac9ac898eb02249c9d6c796/src/pipelines.py#L277
Because the segmentation maps are of such a high quality we can simply use `ndi.label` for this without any additional tricks. In this case it was possible to solve instance segmentation problem with extremely accurate semantic segmentation thanks to loss weighting.
I hope this answers you questions.

**Comment by lixiang-ucas** [comment]
thanks for your help, nice coding!
